import "~/styles/globals.css";
import React from "react";

import { Inter } from "next/font/google";
import { headers } from "next/headers";

import MainNavbar from "~/app/_components/MainNavbar";

import { extractRouterConfig } from "uploadthing/server";
import { chefFileRouter } from "~/app/api/uploadthing/core";

import { Providers } from "~/app/providers";
import { TRPCReactProvider } from "~/trpc/react";

import { Toaster } from "react-hot-toast";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { auth } from "../../auth";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Goose Chef",
  description: "Generated by create-t3-app",
  icons: [{ url: "/images/Logo_round_V2.png" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    //Currently there is no better solution than suppressing the error message: https://github.com/pacocoursey/next-themes/issues/169
    <html lang="en" suppressHydrationWarning>
      <body
        className={`font-sans ${inter.variable} min-h-screen bg-background text-foreground`}
      >
        <NextSSRPlugin routerConfig={extractRouterConfig(chefFileRouter)} />
        <Providers>
          <MainNavbar session={session} />
          <TRPCReactProvider headers={headers()}>
            <div className="mx-auto max-w-screen-xl p-8">
              <Toaster />
              {children}
            </div>
          </TRPCReactProvider>
        </Providers>
      </body>
    </html>
  );
}
